-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 21:36:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cuidapet_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuidapet_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuidapet_db` DEFAULT CHARACTER SET utf8 ;
USE `cuidapet_db` ;

-- -----------------------------------------------------
-- Table `cuidapet_db`.`tb_supplier_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuidapet_db`.`tb_supplier_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(45) NULL,
  `type_category` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuidapet_db`.`tb_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuidapet_db`.`tb_suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `logo` TEXT NULL,
  `address` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `lat_lng` POINT NULL,
  `supplier_categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_supplier_tb_supplier_categories1_idx` (`supplier_categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_supplier_tb_supplier_categories1`
    FOREIGN KEY (`supplier_categories_id`)
    REFERENCES `cuidapet_db`.`tb_supplier_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuidapet_db`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuidapet_db`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` TEXT NULL,
  `type_signup` VARCHAR(45) NULL,
  `ios_token` TEXT NULL,
  `android_token` TEXT NULL,
  `refresh_token` TEXT NULL,
  `img_avatar` TEXT NULL,
  `social_id` TEXT NULL,
  `supplier_id` INT NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp(),
  `updated_at` DATETIME NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_users_tb_supplier_idx` (`supplier_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_tb_users_tb_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `cuidapet_db`.`tb_suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuidapet_db`.`tb_supplier_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuidapet_db`.`tb_supplier_services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `name_service` VARCHAR(200) NULL,
  `service_value` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_supplier_services_tb_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_supplier_services_tb_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `cuidapet_db`.`tb_suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuidapet_db`.`tb_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuidapet_db`.`tb_schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `scheduling_date` DATETIME NULL,
  `users_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `status` CHAR(2) NOT NULL DEFAULT 'P' COMMENT ' \'P=Pendente\\nCN=Confirmada\\nF=Finalizado\\nC=Cancelado\'',
  `name` VARCHAR(200) NULL,
  `name_pet` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_scheduling_tb_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_tb_scheduling_tb_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_scheduling_tb_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `cuidapet_db`.`tb_suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_scheduling_tb_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cuidapet_db`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuidapet_db`.`tb_chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuidapet_db`.`tb_chats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schedules_id` INT NOT NULL,
  `status` CHAR(1) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_chats_tb_scheduling1_idx` (`schedules_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_chats_tb_scheduling1`
    FOREIGN KEY (`schedules_id`)
    REFERENCES `cuidapet_db`.`tb_schedules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuidapet_db`.`schedule_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuidapet_db`.`schedule_services` (
  `schedules_id` INT NOT NULL,
  `supplier_services_id` INT NOT NULL,
  INDEX `fk_schedule_services_tb_scheduling1_idx` (`schedules_id` ASC) VISIBLE,
  INDEX `fk_schedule_services_tb_supplier_services1_idx` (`supplier_services_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_services_tb_scheduling1`
    FOREIGN KEY (`schedules_id`)
    REFERENCES `cuidapet_db`.`tb_schedules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_services_tb_supplier_services1`
    FOREIGN KEY (`supplier_services_id`)
    REFERENCES `cuidapet_db`.`tb_supplier_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
